outsourcing_crawler/urls.py
from django.conf.urls import url
from . import views

app_name = 'outsourcing_crawler'
urlpatterns = [
    url(r'^make_fav/(?P<idx>\d+)/$', views.make_fav, name='make_fav'),
    url(r'^make_nomal/(?P<idx>\d+)/$', views.make_nomal, name='make_nomal'),
    url(r'^make_invis/(?P<idx>\d+)/$', views.make_invis, name='make_invis'),
    url(r'^make_sel_fav/$', views.make_sel_fav, name='make_sel_fav'),
    url(r'^make_sel_nomal/$', views.make_sel_nomal, name='make_sel_nomal'),
    url(r'^make_sel_invis/$', views.make_sel_invis, name='make_sel_invis'),
    url(r'^make_invis_past_biz/$', views.invis_past_biz, name='invis_past_biz'),
    url(r'^show_vis_list/$', views.show_vis_list, name='show_vis_list'),
    url(r'^show_fav_list/$', views.show_fav_list, name='show_fav_list'),
    url(r'^show_sort_list/(?P<sort>\w+)/$', views.show_sort_list, name='show_sort_list'),
    url(r'^show_invis_list/$', views.show_invis_list, name='show_invis_list'),
    url(r'^show_detail/(?P<idx>\d+)/$', views.show_detail, name='show_detail'),
    url(r'^modify_job/(?P<idx>\d+)/$', views.modify_job, name='modify_job'),
    url(r'^add_job/$', views.add_job, name='add_job'),
    url(r'^write_job/$', views.write_job, name='write_job'),
    url(r'^edit_job/(?P<idx>\d+)/$', views.edit_job, name='edit_job'),
]

piano_proj/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from .views import main
from .views import piano_note

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', main, name='main'),
    url(r'^outsourcing_crawler/', include('outsourcing_crawler.urls')),
    url(r'^money_crawler/', include('money_crawler.urls')),
    url(r'^appstore_crawler/', include('appstore_crawler.urls')),
    url(r'^piano_note/$',piano_note, name='piano_note'),
]

outsourcing_crawler/models.py
from django.db import models

class Jobs(models.Model):
    idx = models.AutoField(primary_key=True)
    title = models.CharField(max_length=256)
    url = models.CharField(max_length=512)
    price = models.CharField(max_length=128)
    due = models.CharField(max_length=64)
    period = models.CharField(max_length=64)
    due_flag = models.CharField(max_length=16)
    contents = models.CharField(max_length=4096)
    identify = models.CharField(max_length=512, unique=True, null=False)
    site = models.CharField(max_length=64)
    save_date = models.DateTimeField()
    vis = models.BooleanField()
    fav = models.BooleanField()

outsourcing_crawler/views.py
from django.shortcuts import render
from datetime import datetime
from django.http import HttpResponseRedirect
from .models import *

def show_vis_list(request):
    res_custom = Jobs.objects.filter(vis=True, fav=False, site='custom').order_by('due')
    result = Jobs.objects.filter(vis=True, fav=False, contents=0).order_by('due')
    res_cnt = len(result) + len(res_custom)
    print("vis_list")
    return render(request, 'out_list.html', {'result':result, 'res_custom':res_custom, 'res_cnt':res_cnt})

def show_detail(request,idx):
    result = Jobs.objects.get(idx=idx)
    return render(request, 'out_detail.html', {'result':result } )

def show_fav_list(request):
    favs = Jobs.objects.filter(fav=True).order_by('due')
    print("vis_list")
    return render(request, 'out_fav_list.html', {'favs':favs, 'fav_cnt':len(favs)})

def show_sort_list(request, sort):
    print(sort)
    if sort=='dn':
        favs = Jobs.objects.filter(fav=True).order_by('due')
        result = Jobs.objects.filter(vis=True, fav=False).order_by('due')
        sort = 'up'
    else :
        favs = Jobs.objects.filter(fav=True).order_by('-due')
        result = Jobs.objects.filter(vis=True, fav=False).order_by('-due')
        sort = 'dn'
    print(sort)
    return render(request, 'out_sort_list.html', {'favs':favs, 'result':result, 'sort':sort, 'fav_cnt':len(favs) })

def show_invis_list(request):
    result = Jobs.objects.filter(vis=False).order_by('-save_date')
    print("invis_list")
    return render(request, 'out_invis_list.html', {'result':result, 'res_cnt':len(result)})

def make_fav(request, idx):
    print("fav")
    print(idx)
    if idx :
        result = Jobs.objects.get(idx=idx)
        result.fav = True
        result.vis = True
        result.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def make_nomal(request, idx):
    print("fav")
    print(idx)
    if idx :
        result = Jobs.objects.get(idx=idx)
        result.fav = False
        result.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def make_invis(request, idx):
    if idx :
        result = Jobs.objects.get(idx=idx)
        result.vis = False
        result.fav = False
        result.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def make_sel_fav(request):
    indexs = request.POST.getlist("checks[]")
    for idx in indexs :
        if idx != 'on' :
            result = Jobs.objects.get(idx=idx)
            result.fav = True
            result.vis = True
            result.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def make_sel_invis(request):
    indexs = request.POST.getlist("checks[]")
    for idx in indexs :
        if idx :
            if idx != 'on' :
                result = Jobs.objects.get(idx=idx)
                result.vis = False
                result.fav = False
                result.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def make_sel_nomal(request):
    indexs = request.POST.getlist("checks[]")
    for idx in indexs :
        if idx :
            if idx != 'on' :
                result = Jobs.objects.get(idx=idx)
                result.fav = False
                result.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def invis_past_biz(request):
    now = datetime.now()
    now_date = now.strftime('%Y-%m-%d')
    data = Jobs.objects.filter(vis=True).values()
    if(data) :
        data_cnt = len(data)
        for n in range(data_cnt):
            if len(data[n]['due']) == 10:
                try :
                    due = datetime.strptime(data[n]['due'], '%Y-%m-%d')
                except :
                    continue
                due_date = due.strftime('%Y-%m-%d')
                if now_date > due_date:
                    res = Jobs.objects.get(identify=data[n]['identify'])
                    res.vis = False
                    res.fav = False
                    while True :
                        try :
                            res.save()
                            print("save", due)
                            break
                        except :
                            print("retry")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def write_job(request):
    return render(request, 'write_job.html')

def edit_job(request, idx):
    result = Jobs.objects.get(idx=idx)
    return render(request, 'edit_job.html',{'result':result})

def add_job(request):
    idx = Jobs.objects.all().count() + 1

    data = Jobs(title = request.POST.get("title"),
                url = "/outsourcing_crawler/show_detail/%d" % idx,
                due = '게시물 참조',
                price= request.POST.get("price"),
                period= request.POST.get("period"),
                contents= request.POST.get("contents"),
                due_flag= 'blu',
                identify = "custom_%d" % idx,
                site = 'custom',
                save_date = datetime.now(),
                vis = True,
                fav = False)
    data.save()
    result = Jobs.objects.filter(vis=True, fav=False).order_by('due')
    return render(request, 'out_list.html', {'result':result, 'res_cnt':len(result)} )

def modify_job(request, idx):
    result = Jobs.objects.get(idx=idx)
    result.title = request.POST.get("title")
    result.price= request.POST.get("price")
    result.period= request.POST.get("period")
    result.contents= request.POST.get("contents")
    result.save_date = datetime.now()
    result.save()
    return render(request, 'out_detail.html', {'result':result } )

outsourcing_crawler/templates/edit_job.html
{% extends "outsourcing_crawler/base.html" %}

{% block content %}
<style>
      .business_tb td {
        width: 260px;
      }
      #period, #price {
        width: 215px;
      }
      #title {
        width: 480px;
      }
      #context {
        width: 100%;
        height: 480px;
      }
      .context {

      }
    </style>

<script type="text/javascript">
    function sendData(mode, idx){
        var send_form = document.frm_send_data;
        if(mode == "write"){
            send_form.action = "/outsourcing_crawler/add_job/";
        } else if(mode == "modify"){
            send_form.action = "/outsourcing_crawler/modify_job/"+idx+"/";
        }
        send_form.submit();
    }

    function postnTbody(opt){
      if(opt=='new'){
        $('#fav_body').hide();
        $('#res_body').show();
        $('#send_selnomal_bt').hide();
        $('#send_selfav_bt').show();
      }
      if(opt=='fav'){
        $('#fav_body').show();
        $('#res_body').hide();
        $('#send_selnomal_bt').show();
        $('#send_selfav_bt').hide();
      }
    }
</script>
<table class="menu">
    <tr>
        <td>
            <a href="javascript:location.href= '{% url 'main' %}';">첫 화면으로</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_invis_list' %}';">삭제 된 목록</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:invis_past_biz' %}';">지난 외주 일괄 삭제</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_fav_list' %}' ;">즐겨찾기</a>
            /
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_vis_list' %}';">새 외주</a>
        </td>
    </tr>
</table>
<form method="POST" name="frm_send_data" target="">
    {% csrf_token %}
    <table border="1">
        <tr>
            <td colspan='2'>
                제목 :
                <input type="text" name="title" value="{{result.title}}">
            </td>
        </tr>
        <tr>
            <td>
                기한 :
                <input type="text" name="period" value="{{result.period}}">
            </td>
            <td>
                금액 :
                <input type="text" name="price" value="{{result.price}}">
            </td>
        </tr>
        <tr>
            <td colspan='2' class='contents'>
                내용 :<br>
                <textarea name="contents" cols=50 rows=50 >{{result.contents}}</textarea>
            </td>
        </tr>
    </table>
    <input type="button" value='수정' onclick="javascript:sendData('modify',{{result.idx}})">
    <button ><a href="javascript:location.href= '{% url 'outsourcing_crawler:show_vis_list'%}';">취소</a></button>
</form>
{% endblock content %}

outsourcing_crawler/templates/out_detail.html
{% extends "outsourcing_crawler/base.html" %}

{% block content %}
<style>
      .business_tb td {
        width: 260px;
      }
      #period, #price {
        width: 215px;
      }
      #title {
        width: 480px;
      }
      #context {
        width: 100%;
        height: 480px;
      }
      .context {

      }
    </style>

<script type="text/javascript">
    function sendData(mode, idx){
        var send_form = document.frm_send_data;
        if(mode == "write"){
            send_form.action = "/outsourcing_crawler/add_job/";
        } else if(mode == "edit"){
            send_form.action = "/outsourcing_crawler/edit_job/"+idx+"/";
        }
        send_form.submit();
    }

    function postnTbody(opt){
      if(opt=='new'){
        $('#fav_body').hide();
        $('#res_body').show();
        $('#send_selnomal_bt').hide();
        $('#send_selfav_bt').show();
      }
      if(opt=='fav'){
        $('#fav_body').show();
        $('#res_body').hide();
        $('#send_selnomal_bt').show();
        $('#send_selfav_bt').hide();
      }
    }
</script>
<table class="menu">
    <tr>
        <td>
            <a href="javascript:location.href= '{% url 'main' %}';">첫 화면으로</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_invis_list' %}';">삭제 된 목록</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:invis_past_biz' %}';">지난 외주 일괄 삭제</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_fav_list' %}' ;">즐겨찾기</a>
            /
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_vis_list' %}';">새 외주</a>
        </td>
    </tr>
</table>
<form method="POST" name="frm_send_data" target="">
    {% csrf_token %}
    <table border="1">
        <tr>
            <td colspan='2'>
                제목 :  {{result.title}}
            </td>
        </tr>
        <tr>
            <td>
                기한 :  {{result.period}}
            </td>
            <td>
                금액 :  {{result.price}}
            </td>
        </tr>
        <tr>
            <td colspan='2' class='context'>
                내용 :<br>
                <textarea id="context" cols=50 rows=50 readonly>{{result.contents}}</textarea>
            </td>
        </tr>
    </table>
    <input type="button" value='수정' onclick="javascript:sendData('edit',{{result.idx}})">
    <button ><a href="javascript:location.href= '{% url 'outsourcing_crawler:show_vis_list'%}';">목록으로</a></button>
</form>
{% endblock content %}

outsourcing_crawler/templates/out_fav_list.html
{% extends "outsourcing_crawler/base.html" %}

{% block content %}
<script type="text/javascript">
    var check = false;

    function CheckAll(){
        var chk = document.getElementsByName("checks[]");
        if(check == false){
            check = true;
            for(var i=0; i<chk.length;i++){
                chk[i].checked = true;     //모두 체크
             }
        }else{
            check = false;
            for(var i=0; i<chk.length;i++){
                chk[i].checked = false;     //모두 해제
             }
        }
    }

    function sendData(mode, idx){
        var send_form = document.frm_send_data;
        if(mode == "fav"){
            send_form.action = "/outsourcing_crawler/make_fav/"+idx+"/";
        } else if(mode == "invis"){
            send_form.action = "/outsourcing_crawler/make_invis/"+idx+"/";
        } else if(mode == "nomal"){
            send_form.action = "/outsourcing_crawler/make_nomal/"+idx+"/";
        } else if(mode == "sel_nomal"){
            send_form.action = "{% url 'outsourcing_crawler:make_sel_nomal' %}";
        } else if(mode == "sel_fav"){
            send_form.action = "{% url 'outsourcing_crawler:make_sel_fav' %}";
        } else if(mode == "sel_invis"){
            send_form.action = "{% url 'outsourcing_crawler:make_sel_invis' %}";
        }
        send_form.submit();
    }

    function postnTbody(opt){
      if(opt=='new'){
        $('#fav_body').hide();
        $('#res_body').show();
        $('#send_selnomal_bt').hide();
        $('#send_selfav_bt').show();
      }
      if(opt=='fav'){
        $('#fav_body').show();
        $('#res_body').hide();
        $('#send_selnomal_bt').show();
        $('#send_selfav_bt').hide();
      }
    }
</script>
<table class="menu">
    <tr>
        <td>
            <a href="javascript:location.href= '{% url 'main' %}';">첫 화면으로</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_invis_list' %}';">삭제 된 목록</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:invis_past_biz' %}';">지난 외주 일괄 삭제</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_fav_list' %}' ;">즐겨찾기</a>
            /
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_vis_list' %}';">새 외주</a>
        </td>
    </tr>
</table>
<div class="send_select_div" >
    <input type="button" onclick="javascript:sendData('sel_nomal',0);" id="send_selnomal_bt" value="즐찾해제">
    <input type="button" onclick="javascript:sendData('sel_invis',0);" id="send_selinvis_bt" value="삭제">
</div>
<form method="POST" name="frm_send_data" target="">
    {% csrf_token %}
    <table class="business_tb">
        <tr>
            <th>
                <p>전체 선택</p>
                <input type="checkbox" name="checks[]" onclick="javascript:CheckAll();">
            </th>
            <th>
                <a href="{% url 'outsourcing_crawler:show_sort_list' sort='dn' %}">마감날짜</a>
            </th>
            <th colspan="2">
                즐겨찾기 : {{fav_cnt}} 개
            </th>
            <th>
              사업명
            </th>
            <th>
              출처
            </th>
        </tr>
        {% if res_custom %}
        <tbody id="custom_body" class='show'>
        {% for item in res_custom %}
        <tr>
            <td>
                <input type="checkbox" name="checks[]" value="{{item.idx}}" >
            </td>
            <td class="{{item.due_flag}}" >{{ item.due }}</td>
            <td>
                <input type="button" onclick="javascript:sendData('fav',{{item.idx}})" value="즐겨찾기" style="width: 70pt;">
            </td>
            <td>
                <input type="button" onclick="javascript:sendData('invis',{{item.idx}})" value="삭제">
            </td>
            <td>
                <a href="{{ item.url }}">{{item.title}}</a>
            </td>
            <td>
                {{item.period}}
            </td>
            <td>
                {{item.price}}
            </td>
            <td>{{ item.site }}</td>
        </tr>
        {% endfor %}
        </tbody>
        {% endif %}
        {% if favs %}
        <tbody id="fav_body">
        {% for item in favs %}
        <tr>
            <td>
                <input type="checkbox" name="checks[]" value="{{item.idx}}" >
            </td>
            <td class="{{item.due_flag}}" >{{ item.due }}</td>
            <td>
                <input type="button" onclick="javascript:sendData('nomal',{{item.idx}})" value="즐겨찾기 취소" style="width: 70pt;">
            </td>
            <td>
                <input type="button" onclick="javascript:sendData('invis',{{item.idx}})" value="삭제">
            </td>
            <td>
                <a href="{{ item.url }}">{{item.title}}</a>
            </td>
            <td>{{ item.site }}</td>
        </tr>
        {% endfor %}
      </tbody>
        {% endif %}
    </table>
</form>
{% endblock content %}

outsourcing_crawler/templates/out_list.html
{% extends "outsourcing_crawler/base.html" %}

{% block content %}
<script type="text/javascript">
    var check = false;

    function CheckAll(){
        var chk = document.getElementsByName("checks[]");
        if(check == false){
            check = true;
            for(var i=0; i<chk.length;i++){
                chk[i].checked = true;     //모두 체크
             }
        }else{
            check = false;
            for(var i=0; i<chk.length;i++){
                chk[i].checked = false;     //모두 해제
             }
        }
    }

    function sendData(mode, idx){
        var send_form = document.frm_send_data;
        if(mode == "fav"){
            send_form.action = "/outsourcing_crawler/make_fav/"+idx+"/";
        } else if(mode == "invis"){
            send_form.action = "/outsourcing_crawler/make_invis/"+idx+"/";
        } else if(mode == "nomal"){
            send_form.action = "/outsourcing_crawler/make_nomal/"+idx+"/";
        } else if(mode == "sel_nomal"){
            send_form.action = "{% url 'outsourcing_crawler:make_sel_nomal' %}";
        } else if(mode == "sel_fav"){
            send_form.action = "{% url 'outsourcing_crawler:make_sel_fav' %}";
        } else if(mode == "sel_invis"){
            send_form.action = "{% url 'outsourcing_crawler:make_sel_invis' %}";
        } else if(mode == 'write_job'){
            send_form.action = "{% url 'outsourcing_crawler:write_job' %}";
        }
        send_form.submit();
    }

    function postnTbody(opt){
      if(opt=='new'){
        $('#fav_body').hide();
        $('#res_body').show();
        $('#send_selnomal_bt').hide();
        $('#send_selfav_bt').show();
      }
      if(opt=='fav'){
        $('#fav_body').show();
        $('#res_body').hide();
        $('#send_selnomal_bt').show();
        $('#send_selfav_bt').hide();
      }
    }
</script>
<table class="menu">
    <tr>
        <td>
            <a href="javascript:location.href= '{% url 'main' %}';">첫 화면으로</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_invis_list' %}';">삭제 된 목록</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:invis_past_biz' %}';">지난 외주 일괄 삭제</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_fav_list' %}' ;">즐겨찾기</a>
            /
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_vis_list' %}';">새 외주 구인</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:write_job' %}';">외주 추가</a>
        </td>
    </tr>
</table>
<div class="send_select_div" >
    <input type="button" onclick="javascript:sendData('sel_fav',0);" id="send_selfav_bt" value="즐겨찾기">
    <input type="button" onclick="javascript:sendData('sel_invis',0);" id="send_selinvis_bt" value="삭제">
</div>
<form method="POST" name="frm_send_data" target="">
    {% csrf_token %}
    <table class="business_tb">
        <tr>
            <th>
                <p>전체 선택</p>
                <input type="checkbox" name="checks[]" onclick="javascript:CheckAll();">
            </th>
            <th>
                <a href="{% url 'outsourcing_crawler:show_sort_list' sort='dn' %}">공고 마감날짜</a>
            </th>
            <th colspan="2">
                새 외주 : {{res_cnt}} 개
            </th>
            <th>
                외주명
            </th>
            <th>
                개발기간
            </th>
            <th>
                금액
            </th>
            <th>
              출처
            </th>
        </tr>
        {% if res_custom %}
        <tbody id="custom_body" class='show'>
        {% for item in res_custom %}
        <tr>
            <td>
                <input type="checkbox" name="checks[]" value="{{item.idx}}" >
            </td>
            <td class="{{item.due_flag}}" >{{ item.due }}</td>
            <td>
                <input type="button" onclick="javascript:sendData('fav',{{item.idx}})" value="즐겨찾기" style="width: 70pt;">
            </td>
            <td>
                <input type="button" onclick="javascript:sendData('invis',{{item.idx}})" value="삭제">
            </td>
            <td>
                <a href="{{ item.url }}">{{item.title}}</a>
            </td>
            <td>
                {{item.period}}
            </td>
            <td>
                {{item.price}}
            </td>
            <td>{{ item.site }}</td>
        </tr>
        {% endfor %}
        </tbody>
        {% endif %}
        {% if result %}
        <tbody id="res_body" class='show'>
        {% for item in result %}
        <tr>
            <td>
                <input type="checkbox" name="checks[]" value="{{item.idx}}" >
            </td>
            <td class="{{item.due_flag}}" >{{ item.due }}</td>
            <td>
                <input type="button" onclick="javascript:sendData('fav',{{item.idx}})" value="즐겨찾기" style="width: 70pt;">
            </td>
            <td>
                <input type="button" onclick="javascript:sendData('invis',{{item.idx}})" value="삭제">
            </td>
            <td>
                <a href="{{ item.url }}">{{item.title}}</a>
            </td>
            <td>
                {{item.period}}
            </td>
            <td>
                {{item.price}}
            </td>
            <td>{{ item.site }}</td>
        </tr>
        {% endfor %}
        </tbody>
    {% endif %}
    </table>
</form>
{% endblock content %}

outsourcing_crawler/templates/write_job.html
{% extends "outsourcing_crawler/base.html" %}

{% block content %}
    <style>
      .business_tb td {
        width: 260px;
      }
      #period, #price {
        width: 215px;
      }
      #title {
        width: 480px;
      }
      #context {
        width: 100%;
        height: 480px;
      }
      .context {

      }
    </style>

<script type="text/javascript">
    function sendData(mode, idx){
        var send_form = document.frm_send_data;
        if(mode == "write"){
            send_form.action = "/outsourcing_crawler/add_job/";
        } else if(mode == "modify"){
            send_form.action = "/outsourcing_crawler/modify/"+idx+"/";
        }
        send_form.submit();
    }

    function postnTbody(opt){
      if(opt=='new'){
        $('#fav_body').hide();
        $('#res_body').show();
        $('#send_selnomal_bt').hide();
        $('#send_selfav_bt').show();
      }
      if(opt=='fav'){
        $('#fav_body').show();
        $('#res_body').hide();
        $('#send_selnomal_bt').show();
        $('#send_selfav_bt').hide();
      }
    }
</script>
<table class="menu">
    <tr>
        <td>
            <a href="javascript:location.href= '{% url 'main' %}';">첫 화면으로</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_invis_list' %}';">삭제 된 목록</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:invis_past_biz' %}';">지난 외주 일괄 삭제</a>
        </td>
        <td>
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_fav_list' %}' ;">즐겨찾기</a>
            /
            <a href="javascript:location.href= '{% url 'outsourcing_crawler:show_vis_list' %}';">새 외주</a>
        </td>
    </tr>
</table>
<form method="POST" name="frm_send_data" target="">
    {% csrf_token %}
      <table border="1">
        <tr>
          <td colspan='2'>
          제목 :
          <input type="text" name="title">
          </td>
        </tr>
        <tr>
          <td>
          기한 :
          <input type="text" name="period">
          </td>
          <td>
          금액 :
          <input type="text" name="price">
          </td>
        </tr>
        <tr>
          <td colspan='2' class='contents'>
          내용 :<br>
          <textarea name="contents" cols=50 rows=50></textarea>
          </td>
        </tr>
      </table>
      <input type="button" value='저장' onclick="javascript:sendData('write',0)">
<button ><a href="javascript:location.href= '{% url 'outsourcing_crawler:show_vis_list'%}';">취소</a></button>
    </form>
{% endblock content %}