appstore_crawler/urls.py
from django.conf.urls import url
from . import views

app_name = 'appstore_crawler'
urlpatterns = [
    url(r'^show_list/$', views.show_app_list, name='show_list'),
    url(r'^show_list/detail/(?P<app_id>\d+)/$', views.show_detail, name='show_detail'),
    url(r'^show_icon/$', views.show_app_icon, name='show_icon'),
    url(r'^show_img/$', views.show_app_img, name='show_img'),
    url(r'^show_review/$', views.show_app_review, name='show_review'),
]

piano_proj/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from .views import main
from .views import piano_note

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', main, name='main'),
    url(r'^outsourcing_crawler/', include('outsourcing_crawler.urls')),
    url(r'^money_crawler/', include('money_crawler.urls')),
    url(r'^appstore_crawler/', include('appstore_crawler.urls')),
    url(r'^piano_note/$',piano_note, name='piano_note'),
]

appstore_crawler/models.py
from django.db import models

class AppstoreCrawler(models.Model):
    search_word = models.CharField(max_length=1024)
    search_url = models.CharField(max_length=1024)
    review_url = models.CharField(max_length=1024)

class AppInfo(models.Model):
    app_id = models.CharField(max_length=16, primary_key=True)
    title = models.CharField(max_length=256)
    size = models.CharField(max_length=16)
    lang = models.CharField(max_length=128)
    app_rating = models.CharField(max_length=2)
    icon_url = models.CharField(max_length=512)

class AppImage(models.Model):
    app_id = models.CharField(max_length=16, primary_key=True)
    img_url_0 = models.CharField(max_length=512)
    img_url_1 = models.CharField(max_length=512)
    img_url_2 = models.CharField(max_length=512)
    img_url_3 = models.CharField(max_length=512)
    img_url_4 = models.CharField(max_length=512)
    img_url_5 = models.CharField(max_length=512)
    img_url_6 = models.CharField(max_length=512)
    img_url_7 = models.CharField(max_length=512)
    img_url_8 = models.CharField(max_length=512)
    img_url_9 = models.CharField(max_length=512)

class AppReview(models.Model):
    app_id = models.CharField(max_length=16)
    author = models.CharField(max_length=16)
    rating = models.CharField(max_length=2)
    title = models.CharField(max_length=128)
    review = models.CharField(max_length=512)

appstore_crawler/views.py
from django.shortcuts import render
from .models import *

def show_app_list(request) :
    res = AppInfo.objects.all()
    return render(request,'app_list.html', {'apps':res})

def show_detail(request, app_id) :
    res = AppInfo.objects.filter(app_id=app_id)
    img = AppImage.objects.filter(app_id=app_id)
    review = AppReview.objects.filter(app_id=app_id)
    return render(request,'list_detail.html', {'app':res, 'img':img, 'review':review })

def show_app_icon(request) :
    res = AppInfo.objects.all()
    return render(request,'app_icon.html', {'icons':res})

def show_app_img(request) :
    res = AppImage.objects.all()
    return render(request,'app_img.html', {'imgs':res})

def show_app_review(request) :
    res = AppReview.objects.all()
    print(res)
    return render(request,'app_review.html', {'reviews':res})

appstore_crawler/templates/app_icon.html
{% extends "appstore_crawler/base.html" %}

{% block content %}
<a href="{% url 'main' %}">첫 화면으로</a>
<input type="button" onclick="javascript:location.href= '{% url 'appstore_crawler:show_list' %}';" value="리스트 보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_icon' %}';" value="아이콘 모아보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_img' %}';" value="스크린샷 모아 보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_review' %}';" value="리뷰 모아 보기">
<table class="tbl_appstore">
    <tr>
        <td>
    {% for item in icons %}
            <img src="{{item.icon_url}}" title="{{item.title}}" onclick="javascript:location.href='{% url 'appstore_crawler:show_detail' app_id=item.app_id %}';" width="100" height="100">
    {% endfor %}
        </td>
    </tr>
</table>
{% endblock content %}

appstore_crawler/templates/app_img.html
{% extends "appstore_crawler/base.html" %}

{% block content %}
<a href="{% url 'main' %}">첫 화면으로</a>
<input type="button" onclick="javascript:location.href= '{% url 'appstore_crawler:show_list' %}';" value="리스트 보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_icon' %}';" value="아이콘 모아보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_img' %}';" value="스크린샷 모아 보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_review' %}';" value="리뷰 모아 보기">
<table class="tbl_appstore">
    <tr>
        <td>
            {% for item in imgs %}
            {% if item.img_url_0 %}
            <img src="{{item.img_url_0}}" onclick="javascript:location.href='{% url 'appstore_crawler:show_detail' app_id=item.app_id %}';" width="392" height="696">
            {% endif %}
            {% if item.img_url_1 != 'null' %}
            <img src="{{item.img_url_1}}" onclick="javascript:location.href='{% url 'appstore_crawler:show_detail' app_id=item.app_id %}'" width="392" height="696">
            {% endif %}
            {% if item.img_url_2 != 'null' %}
            <img src="{{item.img_url_2}}" onclick="javascript:location.href='{% url 'appstore_crawler:show_detail' app_id=item.app_id %}'" width="392" height="696">
            {% endif %}
            {% if item.img_url_3 != 'null' %}
            <img src="{{item.img_url_3}}" onclick="javascript:location.href='{% url 'appstore_crawler:show_detail' app_id=item.app_id %}'" width="392" height="696">
            {% endif %}
            {% if item.img_url_4 != 'null' %}
            <img src="{{item.img_url_4}}" onclick="javascript:location.href='{% url 'appstore_crawler:show_detail' app_id=item.app_id %}'" width="392" height="696">
            {% endif %}
            {% if item.img_url_5 != 'null' %}
            <img src="{{item.img_url_5}}" width="392" height="696" onclick="javascript:location.href='{% url 'appstore_crawler:show_detail' app_id=item.app_id %}'">
            {% endif %}
            {% if item.img_url_6 != 'null' %}
            <img src="{{item.img_url_6}}" width="392" height="696" onclick="javascript:location.href='{% url 'appstore_crawler:show_detail' app_id=item.app_id %}'">
            {% endif %}
            {% if item.img_url_7 != 'null' %}
            <img src="{{item.img_url_7}}" width="392" height="696" onclick="javascript:location.href='{% url 'appstore_crawler:show_detail' app_id=item.app_id %}'">
            {% endif %}
            {% if item.img_url_8 != 'null' %}
            <img src="{{item.img_url_8}}" width="392" height="696" onclick="javascript:location.href='{% url 'appstore_crawler:show_detail' app_id=item.app_id %}'">
            {% endif %}
            {% if item.img_url_9 != 'null' %}
            <img src="{{item.img_url_9}}" width="392" height="696" onclick="javascript:location.href='{% url 'appstore_crawler:show_detail' app_id=item.app_id %}'">
            {% endif %}
            {% endfor %}
        </td>
    </tr>
</table>
{% endblock content %}

appstore_crawler/templates/app_list.html
{% extends "appstore_crawler/base.html" %}

{% block content %}
<a href="{% url 'main' %}">첫 화면으로</a>
<input type="button" onclick="javascript:location.href= '{% url 'appstore_crawler:show_list' %}';" value="리스트 보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_icon' %}';" value="아이콘 모아보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_img' %}';" value="스크린샷 모아 보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_review' %}';" value="리뷰 모아 보기">
<table class="tbl_appstore" border="1">
    <tr>
        <th width="25">Icon</th><th> 이름 </th>
    </tr>

    {% if apps %}
    {% for item in apps %}
    <tr>
        <td width="30">
            <img src="{{item.icon_url}}" width="35" height="35">
        </td>
        <td>
            <a href="{% url 'appstore_crawler:show_detail' app_id=item.app_id %}">{{item.title}}</a>
        </td>
    </tr>
    {% endfor %}
    {% endif %}
</table>
{% endblock content %}

appstore_crawler/templates/app_review.html
{% extends "appstore_crawler/base.html" %}

{% block content %}
<a href="{% url 'main' %}">첫 화면으로</a>
<input type="button" onclick="javascript:location.href= '{% url 'appstore_crawler:show_list' %}';" value="리스트 보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_icon' %}';" value="아이콘 모아보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_img' %}';" value="스크린샷 모아 보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_review' %}';" value="리뷰 모아 보기">
    {% for item in reviews %}
    <table class="tbl_appstore" border="1" width="50%">
    <tr>
        <td>
            글쓴이 : {{item.author}}
        </td>
        <td width="30%">
            App ID : <a href="{% url 'appstore_crawler:show_detail' app_id=item.app_id %}">{{item.app_id}}</a>
        </td>
        <td width="30%">
           평점 : {{item.rating}}
        </td>
    </tr>
    <tr>
        <td colspan="3">
            제목 : {{item.title}}
        </td>
    </tr>
    <tr>
        <td colspan="3">
            내용 : {{item.review}}
        </td>
    </tr>
    </table>
    <br>
    <br>
    {% endfor %}
{% endblock content %}

appstore_crawler/templates/list_detail.html
{% extends "appstore_crawler/base.html" %}

{% block content %}
<a href="{% url 'main' %}">첫 화면으로</a>
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_list' %}';" value="리스트 보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_icon' %}';" value="아이콘 모아보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_img' %}';" value="스크린샷 모아 보기">
<input type="button" onclick="javascript:location.href='{% url 'appstore_crawler:show_review' %}';" value="리뷰 모아 보기">
<table class="tbl_appstore">
    {% for item in app %}
    <tr>
        <td colspan="4" >
            {{item.title}}
        </td>
    </tr>
    <tr>
        <td rowspan="4" >
            <img src="{{item.icon_url}}">
        </td>
    </tr>
    <tr>
        <td colspan="2">
            App ID : {{item.app_id}}
        </td>
    </tr>
    <tr>
        <td colspan="2">
            Support Language : {{item.lang}}
        </td>
    </tr>
    <tr>
        <td colspan="2">
            App Size : {{item.size}}
        </td>
    </tr>
    {% endfor %}
    {% for item in img %}
    <tr>
        <td colspan="8">
        {% if item.img_url_0 %}
            <img src="{{item.img_url_0}}">
        {% endif %}
        {% if item.img_url_1 != 'null' %}
            <img src="{{item.img_url_1}}">
        {% endif %}
        {% if item.img_url_2 != 'null' %}
            <img src="{{item.img_url_2}}">
        {% endif %}
        {% if item.img_url_3 != 'null' %}
            <img src="{{item.img_url_3}}">
        {% endif %}
        {% if item.img_url_4 != 'null' %}
            <img src="{{item.img_url_4}}">
        {% endif %}
        {% if item.img_url_5 != 'null' %}
            <img src="{{item.img_url_5}}">
        {% endif %}
        {% if item.img_url_6 != 'null' %}
            <img src="{{item.img_url_6}}">
        {% endif %}
        {% if item.img_url_7 != 'null' %}
            <img src="{{item.img_url_7}}">
        {% endif %}
        {% if item.img_url_8 != 'null' %}
            <img src="{{item.img_url_8}}">
        {% endif %}
        {% if item.img_url_9 != 'null' %}
            <img src="{{item.img_url_9}}">
        {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% for item in review %}
<table class="tbl_appstore" border="1" width="50%">
    <tr>
        <td>
            글쓴이 : {{item.author}}
        </td>
        <td width="30%">
            App ID : <a href="{% url 'appstore_crawler:show_detail' app_id=item.app_id %}">{{item.app_id}}</a>
        </td>
        <td width="30%">
            평점 : {{item.rating}}
        </td>
    </tr>
    <tr>
        <td colspan="3">
            제목 : {{item.title}}
        </td>
    </tr>
    <tr>
        <td colspan="3">
            내용 : {{item.review}}
        </td>
    </tr>
</table>
<br>
<br>
{% endfor %}
{% endblock content %}